# Generated by Django 5.2.1 on 2025-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='url_libro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
