# Generated by Django 5.2.1 on 2025-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_url_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='puntaje',
            field=models.FloatField(),
        ),
    ]
